# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: "psql"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: ~/Work/PSNeoway/docker/db
    ports:
      - 5432:5432
    volumes:
      - ~/Work/PSNeoway/docker/db:/var/lib/postgresql/data